const express = require("express");
const usersRoutes = require("./routes/users");
const app = express();
const PORT = 3000;
const students = [
  {
    id: "F1402PHA01995",
    name: "Suliman Hakimi",
    fatherName: "Mirzamohammad",
    faculty: "Pharmacy",
    semester: "Second",
    role:"STUDENT",
    Province: "LOGAR",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/umis_6896_1692344765.jpg`,
  },
  {
    id: "F1402PHM02003",
    name: "Ahmad Elham Wror",
    fatherName: "Naqibullah",
    Province: "WARDAK",
    role:"STUDENT",
    faculty: "Pharmacy",
    semester: "Second",
    profile: `https://scontent.fkbl6-1.fna.fbcdn.net/v/t39.30808-6/322138681_695406515568983_7627302397244562538_n.jpg?stp=dst-jpg_p526x296&_nc_cat=107&ccb=1-7&_nc_sid=5f2048&_nc_ohc=s0EvKN5CqFwQ7kNvgGDdovH&_nc_ht=scontent.fkbl6-1.fna&oh=00_AfCl4b8tldKr-Io-QjCCW1j3lUtxIHEs4CGJ2NwgodJHBw&oe=6630140F`,
  },
  {
    id: "F1402PHA01987",
    name: "Ahmad Mosawer Mashal",
    fatherName: "Mashal",
    faculty: "Pharmacy",
    role:"STUDENT",
    Province: "KABUL",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01953",
    Province: "KABUL",
    name: "Ahmad Sear Ahmadi",
    role:"STUDENT",
    fatherName: "",
    faculty: "Pharmacy",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01985",
    name: "Ali khan Sardar zada",
    role:"STUDENT",
    fatherName: "Fazel rahman",
    faculty: "Pharmacy",
    semester: "Second",
    Province: "KABUL",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01988",
    name: "Ekramudin Bahawi",
    fatherName: "Muhammad Akbar",
    Province: "KABUL",
    role:"STUDENT",
    faculty: "Pharmacy",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHM01999",
    name: "Farzad Amiriy",
    Province: "KAPISA",
    faculty: "Pharmacy",
    role:"STUDENT",
    fatherName: "Bashir Ahmad",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA02004",
    name: "Hameed Ullah Edokhail",
    fatherName: "Haji shir gul",
    Province: "LOGAR",
    faculty: "Pharmacy",
    role:"STUDENT",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01984",
    name: "Hilal Zahid",
    faculty: "Pharmacy",
    fatherName: "Mohammad Amin",
    role:"STUDENT",
    Province: "NANGARHAR",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01959",
    name: "Juma Gul Hayatzoi",
    faculty: "Pharmacy",
    role:"STUDENT",
    semester: "Second",
    fatherName: "Hayatullah",
    Province: "LOGAR",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHM02002",
    name: "Khan Mohammad Niazi",
    role:"STUDENT",
    faculty: "Pharmacy",
    fatherName: "Jan Mohammad",
    Province: "GHAZNI",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01980",
    name: "Mirwais Sadat",
    faculty: "Pharmacy",
    Province: "KABUL",
    fatherName: "Shah wali",
    role:"STUDENT",
    semester: "Second",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01977",
    name: "Mohammad Anwar OriaKhil",
    faculty: "Pharmacy",
    Province: "KABUL",
    semester: "Second",
    role:"STUDENT",
    fatherName: "Mohammad Azim",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA01971",
    name: "Nasirullah Sulaiman Khil",
    faculty: "Pharmacy",
    semester: "Second",
    fatherName: "Hamidullah	",
    role:"STUDENT",
    Province: "KABUL",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
  {
    id: "F1402PHA02009",
    name: "Roohullah Gawhari",
    fatherName: "Qurban Mohammad",
    faculty: "Pharmacy",
    semester: "Second",
    Province: "PANJSHIR",
    role:"STUDENT",
    profile: `https://mis.cheragh.edu.af/_uploads_/user/default.jpg`,
  },
];
app.use(express.json());
app.set("views", __dirname + "/views");
app.set("view engine", "ejs");

app.get("/", (req, res) => {
  res.render("index", { data: students });
});
app.use("/users", usersRoutes);
app.listen(PORT, () => {
  console.log(`server running on port: http://localhost:${PORT}`);
});
